from typing import Any, Dict

AGENT_METADATA: Dict[str, Dict[str, Any]] = {
    "architect": {
        "id": "architect",
        "name": "Architect",
        "department": "الهندسة",
        "status": "active",
        "fidelity": "live",
        "description": "Architectural integrity and system design.",
        "capabilities": ["Design review", "System topology", "Integrity checks"],
        "signals": ["Live"],
        "role": "architect",
    },
    "engineer": {
        "id": "engineer",
        "name": "Engineer",
        "department": "العمليات",
        "status": "active",
        "fidelity": "live",
        "description": "GitOps / Version Control status.",
        "capabilities": ["GitOps posture", "Branch hygiene", "Deploy gates"],
        "signals": ["Live"],
        "role": "engineer",
    },
    "policy": {
        "id": "policy",
        "name": "Policy Agent",
        "department": "الحوكمة",
        "status": "active",
        "fidelity": "live",
        "description": "Policy Editor · Rules Engine",
        "capabilities": ["Policy edit", "Rules validation", "Escalation to HDAL"],
        "signals": ["Policy-Engine"],
        "role": "policy",
    },
    "sentinel": {
        "id": "sentinel",
        "name": "Sentinel",
        "department": "الأمن",
        "status": "active",
        "fidelity": "live",
        "description": "Drift Monitor · Pattern Alerts",
        "capabilities": ["Risk scans", "Drift detection", "Pattern alerts"],
        "signals": ["/ws/scp", "patterns/alerts"],
        "role": "sentinel",
    },
    "failure": {
        "id": "failure",
        "name": "Failure Agent",
        "department": "الأمن",
        "status": "active",
        "fidelity": "live",
        "description": "Failure mode detection and risk analysis.",
        "capabilities": ["FMEA", "Risk detection", "Side effect analysis"],
        "signals": ["Signals"],
        "role": "failure",
    },
    "guardian": {
        "id": "guardian",
        "name": "Concept Guardian",
        "department": "الأمن",
        "status": "active",
        "fidelity": "live",
        "description": "Protects core system concepts and integrity.",
        "capabilities": [
            "Concept integrity",
            "Boundary checks",
            "Philosophy compliance",
        ],
        "signals": ["Manifesto"],
        "role": "guardian",
    },
    "builder": {
        "id": "builder",
        "name": "Builder",
        "department": "العمليات",
        "status": "active",
        "fidelity": "live",
        "description": "Code generation and scaffolding tasks.",
        "capabilities": ["Scaffold code", "Draft PR plans", "Path inference"],
        "signals": ["Generator"],
        "role": "builder",
    },
    "verification": {
        "id": "verification",
        "name": "Verification Agent",
        "department": "الجودة",
        "status": "active",
        "fidelity": "live",
        "description": "Comprehensive code verification and security scanning.",
        "capabilities": [
            "Security audit",
            "Quality checks",
            "Dependency scan",
            "Best practices",
        ],
        "signals": ["Security feed"],
        "role": "verification",
    },
    "testing": {
        "id": "testing",
        "name": "Testing Agent",
        "department": "الجودة",
        "status": "active",
        "fidelity": "live",
        "description": "Automated test generation and execution.",
        "capabilities": [
            "Test generation",
            "Edge case detection",
            "Coverage analysis",
            "Pytest orchestration",
        ],
        "signals": ["Test results"],
        "role": "testing",
    },
    "specialist": {
        "id": "specialist",
        "name": "Code Specialist",
        "department": "الهندسة",
        "status": "active",
        "fidelity": "live",
        "description": "Deep code analysis and domain expertise.",
        "capabilities": ["Static analysis", "Refactoring", "Optimization"],
        "signals": ["Lints"],
        "role": "specialist",
    },
}


def get_agent_metadata(role_value: str) -> Dict[str, Any]:
    """Returns metadata for a given agent role value, with fallback."""
    return AGENT_METADATA.get(
        role_value,
        {
            "id": role_value,
            "name": role_value.title(),
            "department": "Unknown",
            "status": "active",
            "fidelity": "simulated",
            "description": f"Registered agent: {role_value}",
            "capabilities": [],
            "signals": [],
            "role": role_value,
        },
    )
